#Welcome to join for the first time
welcomeFirstJoin:
  enabled: true
  message: "&dNew players &e%player% &dare welcome to join the server!"

#If you don't turn on the following functions, you won't modify the information instead of turning it off
#Players join the server
join:
  enabled: true
  message: "&a[+]%player%"

#The player leaves the server
quit:
  enabled: true
  message: "&c[-]%player%"

#Compatibility mode (if the function does not work properly, you can try toggling this option)
compatible: true